//! `package_matrix` — release packaging descriptor generator (BharatCode v94).
//!
//! Pure, offline helpers that turn a built BharatCode release binary into the
//! packaging artifacts a release pipeline needs:
//!
//!   * [`nfpm_config`]   — an nfpm-style YAML descriptor that produces both a
//!                         `.deb` and an `.rpm` for a given version + arch.
//!   * [`homebrew_formula`] — a minimal Homebrew formula stub embedding the
//!                         release version and the tarball's SHA-256.
//!   * [`sha256sums`]    — a GNU-coreutils-style `SHA256SUMS` manifest from a
//!                         list of `(name, hex)` pairs.
//!   * [`expected_asset_names`] — the exact `bharatcode-<triple>.tar.bz2` / `.zip`
//!                         asset names that the self-updater in
//!                         `commands/update.rs` `asset_name()` expects, kept in
//!                         lockstep so a rename in either place fails CI.
//!
//! Everything here is a pure function over its inputs: no network, no
//! filesystem writes, no new dependencies. The actual artifacts are emitted by
//! release tooling that calls these helpers; the `doctor` command only consumes
//! [`expected_asset_names`] for a read-only release-readiness row.
//!
//! Original BharatCode work; not ported from any third party.

/// Package metadata shared by every emitted descriptor. Centralised so the deb,
/// rpm, and Homebrew outputs never drift from one another.
const PACKAGE_NAME: &str = "bharatcode";
const PACKAGE_LICENSE: &str = "Apache-2.0";
const PACKAGE_VENDOR: &str = "BharatCode";
const PACKAGE_MAINTAINER: &str = "BharatCode <release@bharatcode.dev>";
const PACKAGE_HOMEPAGE: &str = "https://bharatcode.dev";
const PACKAGE_DESCRIPTION: &str = "BharatCode CLI - an India-first AI coding agent";

/// The release triples BharatCode ships assets for, paired with the archive
/// extension the self-updater downloads. Kept in lockstep with the
/// `asset_name()` match arms in `commands/update.rs`: every Unix triple is a
/// `.tar.bz2`, every Windows triple is a `.zip`.
const RELEASE_TRIPLES: &[(&str, &str)] = &[
    ("aarch64-apple-darwin", "tar.bz2"),
    ("x86_64-apple-darwin", "tar.bz2"),
    ("x86_64-unknown-linux-gnu", "tar.bz2"),
    ("aarch64-unknown-linux-gnu", "tar.bz2"),
    ("x86_64-unknown-linux-musl", "tar.bz2"),
    ("aarch64-unknown-linux-musl", "tar.bz2"),
    ("x86_64-pc-windows-msvc", "zip"),
];

/// Build the release asset name for a single `(triple, ext)` pair. This is the
/// single source of truth for asset naming on the packaging side and must match
/// `asset_name()` in `commands/update.rs` byte-for-byte.
fn asset_name_for(triple: &str, ext: &str) -> String {
    format!("{PACKAGE_NAME}-{triple}.{ext}")
}

/// The exact set of release asset names BharatCode publishes, in a stable order.
///
/// These are the same strings the self-updater's `asset_name()` resolves to at
/// compile time for each target. A unit test asserts string equality against
/// the values `asset_name()` builds, so renaming an asset in either place
/// without updating the other fails CI.
pub fn expected_asset_names() -> Vec<String> {
    RELEASE_TRIPLES
        .iter()
        .map(|(triple, ext)| asset_name_for(triple, ext))
        .collect()
}

/// Map a release triple onto the package architecture nfpm expects.
///
/// nfpm uses Go's `GOARCH` names (`amd64`, `arm64`), which differ from the Rust
/// triple's leading component (`x86_64`, `aarch64`). Unknown architectures fall
/// back to the raw input so the descriptor is still well-formed.
fn nfpm_arch(arch: &str) -> &str {
    match arch {
        "x86_64" | "amd64" => "amd64",
        "aarch64" | "arm64" => "arm64",
        other => other,
    }
}

/// Emit an nfpm-style YAML descriptor that builds both a `.deb` and an `.rpm`
/// for the given `version` and `arch`.
///
/// `arch` is a Rust-style architecture (`x86_64` / `aarch64`); it is mapped to
/// the nfpm/Go `GOARCH` value in the descriptor while still being echoed in a
/// comment for traceability. The package name is `bharatcode`, the license is
/// `Apache-2.0`, and the vendor is `BharatCode`.
pub fn nfpm_config(version: &str, arch: &str) -> String {
    let go_arch = nfpm_arch(arch);
    format!(
        "# nfpm descriptor for {PACKAGE_NAME} {version} ({arch})\n\
         # Generated by package_matrix; build with: nfpm package -p deb && nfpm package -p rpm\n\
         name: {PACKAGE_NAME}\n\
         arch: {go_arch}\n\
         platform: linux\n\
         version: \"{version}\"\n\
         section: utils\n\
         priority: optional\n\
         maintainer: {PACKAGE_MAINTAINER}\n\
         vendor: {PACKAGE_VENDOR}\n\
         homepage: {PACKAGE_HOMEPAGE}\n\
         license: {PACKAGE_LICENSE}\n\
         description: |\n  \
           {PACKAGE_DESCRIPTION}\n\
         contents:\n  \
           - src: ./{PACKAGE_NAME}\n    \
             dst: /usr/bin/{PACKAGE_NAME}\n    \
             file_info:\n      \
               mode: 0755\n"
    )
}

/// Emit a minimal Homebrew formula stub for the given `version` and tarball
/// `sha256`.
///
/// The formula embeds the version and the SHA-256 of the macOS release tarball
/// so `brew install` can verify the download. It is a stub: the URL points at
/// the conventional GitHub release path and the install step copies the single
/// `bharatcode` binary into `bin`.
pub fn homebrew_formula(version: &str, sha256: &str) -> String {
    let darwin_asset = asset_name_for("x86_64-apple-darwin", "tar.bz2");
    format!(
        "# Homebrew formula for {PACKAGE_NAME} {version}\n\
         # License: {PACKAGE_LICENSE}\n\
         class Bharatcode < Formula\n  \
           desc \"{PACKAGE_DESCRIPTION}\"\n  \
           homepage \"{PACKAGE_HOMEPAGE}\"\n  \
           url \"{PACKAGE_HOMEPAGE}/releases/download/v{version}/{darwin_asset}\"\n  \
           version \"{version}\"\n  \
           sha256 \"{sha256}\"\n  \
           license \"{PACKAGE_LICENSE}\"\n\n  \
           def install\n    \
             bin.install \"{PACKAGE_NAME}\"\n  \
           end\n\n  \
           test do\n    \
             system \"#{{bin}}/{PACKAGE_NAME}\", \"--version\"\n  \
           end\n\
         end\n"
    )
}

/// Format a `SHA256SUMS` manifest from a list of `(name, hex)` pairs, GNU
/// coreutils style: each line is `<hex><two spaces><name>`, one per line, in the
/// order supplied. The double space is the binary-mode separator `sha256sum -c`
/// expects.
pub fn sha256sums(files: &[(&str, &str)]) -> String {
    let mut out = String::new();
    for (name, hex) in files {
        out.push_str(hex);
        out.push_str("  ");
        out.push_str(name);
        out.push('\n');
    }
    out
}

/// Read-only release-readiness check surfaced in `bharatcode doctor`.
///
/// Verifies that every [`expected_asset_names`] entry is well-formed (carries
/// the `bharatcode-` prefix and a known archive extension) and that the running
/// binary's `--version` (`CARGO_PKG_VERSION`) parses as a `major.minor.patch`
/// triplet. Returns a [`Status`] plus a human-readable message. Purely
/// introspective: it touches no network, filesystem, or config and never gates
/// the doctor run.
pub fn release_readiness() -> (crate::commands::doctor_checks::Status, String) {
    use crate::commands::doctor_checks::Status;

    let version = env!("CARGO_PKG_VERSION");
    let names = expected_asset_names();

    let all_well_formed = names
        .iter()
        .all(|n| n.starts_with("bharatcode-") && (n.ends_with(".tar.bz2") || n.ends_with(".zip")));
    let version_ok = version_is_parseable(version);

    let lbl = "Release packaging";
    if all_well_formed && version_ok {
        (
            Status::Ok,
            format!(
                "{lbl}: v{version}, {} asset names match the self-updater",
                names.len()
            ),
        )
    } else if !version_ok {
        (
            Status::Warn,
            format!("{lbl}: running version '{version}' is not a parseable major.minor.patch"),
        )
    } else {
        (
            Status::Warn,
            format!("{lbl}: one or more expected asset names are malformed"),
        )
    }
}

/// Whether `version` looks like a `major.minor.patch` semver core (each
/// component a non-empty run of ASCII digits). A trailing pre-release/build
/// suffix on the patch (e.g. `1.2.3-rc1`) is tolerated.
fn version_is_parseable(version: &str) -> bool {
    let mut parts = version.split('.');
    let (major, minor, patch) = match (parts.next(), parts.next(), parts.next(), parts.next()) {
        (Some(a), Some(b), Some(c), None) => (a, b, c),
        _ => return false,
    };
    let numeric = |s: &str| !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit());
    let patch_core = patch.split(['-', '+']).next().unwrap_or("");
    numeric(major) && numeric(minor) && numeric(patch_core)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nfpm_config_has_name_license_and_arch() {
        let yaml = nfpm_config("1.2.3", "x86_64");
        assert!(yaml.contains("name: bharatcode"), "package name missing");
        assert!(yaml.contains("license: Apache-2.0"), "license missing");
        // Rust arch echoed in the header comment, GOARCH used in the descriptor.
        assert!(yaml.contains("x86_64"), "rust arch not echoed");
        assert!(yaml.contains("arch: amd64"), "nfpm GOARCH missing");
        assert!(yaml.contains("vendor: BharatCode"), "vendor missing");
        assert!(yaml.contains("version: \"1.2.3\""), "version missing");

        let arm = nfpm_config("1.2.3", "aarch64");
        assert!(arm.contains("arch: arm64"), "arm64 GOARCH missing");
    }

    #[test]
    fn homebrew_formula_embeds_version_and_sha() {
        let sha = "abc123def456";
        let formula = homebrew_formula("9.9.9", sha);
        assert!(formula.contains(sha), "sha256 not embedded");
        assert!(
            formula.contains("version \"9.9.9\""),
            "version not embedded"
        );
        assert!(
            formula.contains("class Bharatcode < Formula"),
            "formula class missing"
        );
        assert!(
            formula.contains("license \"Apache-2.0\""),
            "license missing"
        );
        assert!(formula.contains("v9.9.9/"), "release url version missing");
    }

    #[test]
    fn sha256sums_is_gnu_coreutils_style() {
        let files = [
            ("bharatcode-x86_64-unknown-linux-gnu.tar.bz2", "deadbeef"),
            ("bharatcode-x86_64-pc-windows-msvc.zip", "cafebabe"),
        ];
        let manifest = sha256sums(&files);
        // `<hex>  <name>` — exactly two spaces (binary-mode separator).
        assert_eq!(
            manifest,
            "deadbeef  bharatcode-x86_64-unknown-linux-gnu.tar.bz2\n\
             cafebabe  bharatcode-x86_64-pc-windows-msvc.zip\n"
        );
        for line in manifest.lines() {
            let (hex, name) = line.split_once("  ").expect("two-space separator");
            assert!(!hex.contains(' '), "hex must not contain spaces");
            assert!(!name.is_empty(), "name must be present");
        }
    }

    #[test]
    fn expected_asset_names_match_update_asset_name() {
        // These literals mirror the `asset_name()` match arms in
        // `commands/update.rs`. String equality so any drift fails CI.
        let names = expected_asset_names();
        assert!(names.contains(&"bharatcode-aarch64-apple-darwin.tar.bz2".to_string()));
        assert!(names.contains(&"bharatcode-x86_64-apple-darwin.tar.bz2".to_string()));
        assert!(names.contains(&"bharatcode-x86_64-unknown-linux-gnu.tar.bz2".to_string()));
        assert!(names.contains(&"bharatcode-aarch64-unknown-linux-gnu.tar.bz2".to_string()));
        assert!(names.contains(&"bharatcode-x86_64-unknown-linux-musl.tar.bz2".to_string()));
        assert!(names.contains(&"bharatcode-aarch64-unknown-linux-musl.tar.bz2".to_string()));
        assert!(names.contains(&"bharatcode-x86_64-pc-windows-msvc.zip".to_string()));

        // Full, ordered equality — the exact x86_64/aarch64 linux+mac + windows
        // set the self-updater builds.
        let expected = vec![
            "bharatcode-aarch64-apple-darwin.tar.bz2".to_string(),
            "bharatcode-x86_64-apple-darwin.tar.bz2".to_string(),
            "bharatcode-x86_64-unknown-linux-gnu.tar.bz2".to_string(),
            "bharatcode-aarch64-unknown-linux-gnu.tar.bz2".to_string(),
            "bharatcode-x86_64-unknown-linux-musl.tar.bz2".to_string(),
            "bharatcode-aarch64-unknown-linux-musl.tar.bz2".to_string(),
            "bharatcode-x86_64-pc-windows-msvc.zip".to_string(),
        ];
        assert_eq!(names, expected);
    }

    #[test]
    fn release_readiness_is_ok_for_running_binary() {
        let (status, msg) = release_readiness();
        assert_eq!(status, crate::commands::doctor_checks::Status::Ok);
        assert!(msg.contains("Release packaging"));
    }

    #[test]
    fn version_parse_accepts_semver_core_and_prerelease() {
        assert!(version_is_parseable("0.7.0"));
        assert!(version_is_parseable("1.2.3-rc1"));
        assert!(version_is_parseable("10.20.30+build5"));
        assert!(!version_is_parseable("1.2"));
        assert!(!version_is_parseable("1.2.3.4"));
        assert!(!version_is_parseable("x.y.z"));
        assert!(!version_is_parseable(""));
    }
}
